spring.application.name=courseSearch


#spring.elasticsearch.index.prefix=courses
#spring.elasticsearch.connection-timeout=30000
#spring.elasticsearch.socket-timeout=30000

 
#
#spring.elasticsearch.uris=http://localhost:9200
#spring.elasticsearch.username=elastic
#spring.elasticsearch.password=changeme
#spring.data.elasticsearch.repositories.enabled=true
#spring.elasticsearch.index.create=true



spring.elasticsearch.uris= http://localhost:9200

spring.data.elasticsearch.repositories.enabled=true
logging.level.web=debug



# 8.11.1 - es
# <version>4.0.3</version> - sb