spring.application.name=courseSearch


#spring.elasticsearch.index.prefix=courses
#spring.elasticsearch.connection-timeout=30000
#spring.elasticsearch.socket-timeout=30000

 




spring.elasticsearch.uris= http://localhost:9200

spring.data.elasticsearch.repositories.enabled=true
logging.level.web=debug



